name: HubTools
author: iTrooz_, Narcos
description: Utilités pour le Hub
version: -1
main: fr.entasia.hubtools.Main
depend: [Libraries]
softdepend: [Multiverse-Core, Vault]
api-version: '1.15'
commands:
  buildtoggle:
  menu:
    aliases: [entasia]
  hubtools:
    aliases: [hubtool]
  spawn:
    aliases: [hub, lob, lobby]

  creatif:
  entagames:
  skyblock: